
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores.FS;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int tIgual = 11;
  public static final int tAumen = 18;
  public static final int tDiv = 8;
  public static final int tDec = 16;
  public static final int tParOpen = 12;
  public static final int tCad = 15;
  public static final int tVar = 21;
  public static final int tPtoComa = 5;
  public static final int tMas = 6;
  public static final int tElev = 10;
  public static final int tImprimir = 2;
  public static final int tDecremen = 19;
  public static final int EOF = 0;
  public static final int unarioNeg = 20;
  public static final int tFalse = 4;
  public static final int error = 1;
  public static final int tEntero = 14;
  public static final int tTrue = 3;
  public static final int tParClose = 13;
  public static final int tId = 17;
  public static final int tPor = 9;
  public static final int tComa = 22;
  public static final int tMenos = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tImprimir",
  "tTrue",
  "tFalse",
  "tPtoComa",
  "tMas",
  "tMenos",
  "tDiv",
  "tPor",
  "tElev",
  "tIgual",
  "tParOpen",
  "tParClose",
  "tEntero",
  "tCad",
  "tDec",
  "tId",
  "tAumen",
  "tDecremen",
  "unarioNeg",
  "tVar",
  "tComa"
  };
}

