
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores.FS;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int res_crear_ventana = 58;
  public static final int tSelecciona = 43;
  public static final int tIgual = 11;
  public static final int tParOpen = 12;
  public static final int tMenorIgual = 27;
  public static final int tPtoComa = 5;
  public static final int res_buscar = 67;
  public static final int tMenos = 7;
  public static final int res_Descendente = 53;
  public static final int tEntero = 14;
  public static final int tBreak = 44;
  public static final int res_todos = 69;
  public static final int tComa = 22;
  public static final int res_Ascendente = 54;
  public static final int tPunto = 52;
  public static final int tTrue = 3;
  public static final int tDiv = 8;
  public static final int res_crear_boton = 64;
  public static final int tMas = 6;
  public static final int umenos = 23;
  public static final int tReturn = 48;
  public static final int tDecremen = 19;
  public static final int res_crear_contenedor = 59;
  public static final int tDistinto = 29;
  public static final int tSi = 35;
  public static final int unarioNeg = 20;
  public static final int tNulo = 30;
  public static final int tMenorQue = 25;
  public static final int tMayorIgual = 26;
  public static final int res_alClick = 65;
  public static final int tSumaAsig = 31;
  public static final int res_reduce = 68;
  public static final int tLlvClose = 40;
  public static final int res_map = 71;
  public static final int tDiviAsig = 34;
  public static final int tCorchClose = 51;
  public static final int tAumen = 18;
  public static final int tInterrogacion = 37;
  public static final int tElev = 10;
  public static final int tSino = 36;
  public static final int tCaso = 41;
  public static final int tDosPuntos = 38;
  public static final int tAnd = 45;
  public static final int tImprimir = 2;
  public static final int tMultipliAsig = 33;
  public static final int tCorchOpen = 50;
  public static final int EOF = 0;
  public static final int res_crear_texto = 60;
  public static final int res_maximo = 56;
  public static final int tCad = 15;
  public static final int res_filter = 66;
  public static final int tDefecto = 42;
  public static final int tRestaAsig = 32;
  public static final int res_alguno = 70;
  public static final int tLlvOpen = 39;
  public static final int tIgualDoble = 28;
  public static final int tParClose = 13;
  public static final int res_crear_caja_texto = 63;
  public static final int error = 1;
  public static final int res_obtenerPorEtiqueta = 62;
  public static final int tFalse = 4;
  public static final int tMayorQue = 24;
  public static final int res_minimo = 57;
  public static final int tFuncion = 49;
  public static final int tPor = 9;
  public static final int tOr = 46;
  public static final int res_Invertir = 55;
  public static final int tNot = 47;
  public static final int tId = 17;
  public static final int res_leerGxml = 61;
  public static final int tDec = 16;
  public static final int tVar = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tImprimir",
  "tTrue",
  "tFalse",
  "tPtoComa",
  "tMas",
  "tMenos",
  "tDiv",
  "tPor",
  "tElev",
  "tIgual",
  "tParOpen",
  "tParClose",
  "tEntero",
  "tCad",
  "tDec",
  "tId",
  "tAumen",
  "tDecremen",
  "unarioNeg",
  "tVar",
  "tComa",
  "umenos",
  "tMayorQue",
  "tMenorQue",
  "tMayorIgual",
  "tMenorIgual",
  "tIgualDoble",
  "tDistinto",
  "tNulo",
  "tSumaAsig",
  "tRestaAsig",
  "tMultipliAsig",
  "tDiviAsig",
  "tSi",
  "tSino",
  "tInterrogacion",
  "tDosPuntos",
  "tLlvOpen",
  "tLlvClose",
  "tCaso",
  "tDefecto",
  "tSelecciona",
  "tBreak",
  "tAnd",
  "tOr",
  "tNot",
  "tReturn",
  "tFuncion",
  "tCorchOpen",
  "tCorchClose",
  "tPunto",
  "res_Descendente",
  "res_Ascendente",
  "res_Invertir",
  "res_maximo",
  "res_minimo",
  "res_crear_ventana",
  "res_crear_contenedor",
  "res_crear_texto",
  "res_leerGxml",
  "res_obtenerPorEtiqueta",
  "res_crear_caja_texto",
  "res_crear_boton",
  "res_alClick",
  "res_filter",
  "res_buscar",
  "res_reduce",
  "res_todos",
  "res_alguno",
  "res_map"
  };
}

