
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package olc2_Tarea1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int tPComa = 8;
  public static final int tLlvCls = 6;
  public static final int tInt = 2;
  public static final int tChar = 4;
  public static final int tId = 7;
  public static final int EOF = 0;
  public static final int tBool = 3;
  public static final int tLlvOpn = 5;
  public static final int error = 1;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tInt",
  "tBool",
  "tChar",
  "tLlvOpn",
  "tLlvCls",
  "tId",
  "tPComa"
  };
}

