
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores.GXML;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int res_slash = 14;
  public static final int res_MenorQue = 16;
  public static final int res_color = 21;
  public static final int res_defecto = 9;
  public static final int tDec = 4;
  public static final int tCad = 3;
  public static final int res_MayorQue = 17;
  public static final int tNumerico = 31;
  public static final int res_Igual = 15;
  public static final int res_tipo = 20;
  public static final int res_control = 7;
  public static final int res_falso = 30;
  public static final int res_borde = 28;
  public static final int res_ancho = 27;
  public static final int res_alto = 26;
  public static final int res_enviar = 12;
  public static final int res_contenedor = 5;
  public static final int EOF = 0;
  public static final int res_listaDatos = 10;
  public static final int res_texto = 6;
  public static final int res_verdadero = 29;
  public static final int res_id = 8;
  public static final int tTexto = 19;
  public static final int error = 1;
  public static final int res_y = 25;
  public static final int res_x = 24;
  public static final int res_accion_inicial = 22;
  public static final int tEntero = 2;
  public static final int res_dato = 11;
  public static final int res_ventana = 13;
  public static final int res_accion_final = 23;
  public static final int tId = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tEntero",
  "tCad",
  "tDec",
  "res_contenedor",
  "res_texto",
  "res_control",
  "res_id",
  "res_defecto",
  "res_listaDatos",
  "res_dato",
  "res_enviar",
  "res_ventana",
  "res_slash",
  "res_Igual",
  "res_MenorQue",
  "res_MayorQue",
  "tId",
  "tTexto",
  "res_tipo",
  "res_color",
  "res_accioninicial",
  "res_accionfinal",
  "res_x",
  "res_y",
  "res_alto",
  "res_ancho",
  "res_borde",
  "res_verdadero",
  "res_falso",
  "tNumerico"
  };
}

