
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores.GXML;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int res_accion = 35;
  public static final int res_maximo = 33;
  public static final int res_llvClose = 17;
  public static final int res_id = 10;
  public static final int tCad = 2;
  public static final int res_cursiva = 31;
  public static final int res_negrita = 30;
  public static final int res_llvOpen = 16;
  public static final int res_listaDatos = 36;
  public static final int res_tipo = 12;
  public static final int res_importar = 7;
  public static final int res_path = 43;
  public static final int res_dato = 37;
  public static final int res_color = 13;
  public static final int res_fuente = 28;
  public static final int res_enviar = 42;
  public static final int res_MayorQue = 6;
  public static final int tTexto = 3;
  public static final int res_nombre = 27;
  public static final int res_falso = 25;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int res_auto_reproduccion = 44;
  public static final int res_multimedia = 39;
  public static final int res_texto = 26;
  public static final int tNumerico = 4;
  public static final int res_contenedor = 18;
  public static final int res_defecto = 38;
  public static final int res_borde = 23;
  public static final int res_y = 20;
  public static final int res_x = 19;
  public static final int res_control = 32;
  public static final int res_tam = 29;
  public static final int res_boton = 40;
  public static final int res_accionInicial = 14;
  public static final int res_minimo = 34;
  public static final int res_MenorQue = 5;
  public static final int res_Igual = 11;
  public static final int res_verdadero = 24;
  public static final int res_slash = 8;
  public static final int res_alto = 21;
  public static final int res_ancho = 22;
  public static final int res_referencia = 41;
  public static final int res_ventana = 9;
  public static final int res_accionFinal = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tCad",
  "tTexto",
  "tNumerico",
  "res_MenorQue",
  "res_MayorQue",
  "res_importar",
  "res_slash",
  "res_ventana",
  "res_id",
  "res_Igual",
  "res_tipo",
  "res_color",
  "res_accionInicial",
  "res_accionFinal",
  "res_llvOpen",
  "res_llvClose",
  "res_contenedor",
  "res_x",
  "res_y",
  "res_alto",
  "res_ancho",
  "res_borde",
  "res_verdadero",
  "res_falso",
  "res_texto",
  "res_nombre",
  "res_fuente",
  "res_tam",
  "res_negrita",
  "res_cursiva",
  "res_control",
  "res_maximo",
  "res_minimo",
  "res_accion",
  "res_listaDatos",
  "res_dato",
  "res_defecto",
  "res_multimedia",
  "res_boton",
  "res_referencia",
  "res_enviar",
  "res_path",
  "res_auto_reproduccion"
  };
}

