
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores.GXML;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int res_maximo = 32;
  public static final int res_accion = 34;
  public static final int res_llvClose = 36;
  public static final int res_id = 7;
  public static final int tCad = 3;
  public static final int res_cursiva = 31;
  public static final int res_negrita = 30;
  public static final int res_llvOpen = 35;
  public static final int res_listaDatos = 9;
  public static final int res_tipo = 19;
  public static final int res_dato = 10;
  public static final int res_color = 20;
  public static final int res_fuente = 28;
  public static final int res_enviar = 11;
  public static final int res_MayorQue = 16;
  public static final int tTexto = 18;
  public static final int res_falso = 27;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int res_texto = 5;
  public static final int tNumerico = 2;
  public static final int res_contenedor = 4;
  public static final int res_borde = 25;
  public static final int res_defecto = 8;
  public static final int res_y = 22;
  public static final int res_x = 21;
  public static final int tId = 17;
  public static final int res_control = 6;
  public static final int res_tam = 29;
  public static final int res_accionInicial = 37;
  public static final int res_minimo = 33;
  public static final int res_MenorQue = 15;
  public static final int res_Igual = 14;
  public static final int res_verdadero = 26;
  public static final int res_slash = 13;
  public static final int res_alto = 23;
  public static final int res_ancho = 24;
  public static final int res_ventana = 12;
  public static final int res_accionFinal = 38;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tNumerico",
  "tCad",
  "res_contenedor",
  "res_texto",
  "res_control",
  "res_id",
  "res_defecto",
  "res_listaDatos",
  "res_dato",
  "res_enviar",
  "res_ventana",
  "res_slash",
  "res_Igual",
  "res_MenorQue",
  "res_MayorQue",
  "tId",
  "tTexto",
  "res_tipo",
  "res_color",
  "res_x",
  "res_y",
  "res_alto",
  "res_ancho",
  "res_borde",
  "res_verdadero",
  "res_falso",
  "res_fuente",
  "res_tam",
  "res_negrita",
  "res_cursiva",
  "res_maximo",
  "res_minimo",
  "res_accion",
  "res_llvOpen",
  "res_llvClose",
  "res_accionInicial",
  "res_accionFinal"
  };
}

